### ISSUE TITLE
No more id attribute in  all <a > tags

### ISSUE THREAD

**Issue by jfiger** [toshimaru/jekyll-toc#105]
Updating from jekyll-toc 0.4.0 to 13.1.0, I found the following issue: **id attribute missing** in all `<a>` tags inside `<h>` tags
**generated by 0.4.0**
`<h2><a id="historique-du-site-depuis-1970" class="anchor" href="#historique-du-site-depuis-1970" aria-hidden="true"><span class="octicon octicon-link"></span></a>Historique du site depuis 1970</h2>`

**generated by 13.1.0**
`<h2><a class="anchor" href="#historique-du-site-depuis-1970" aria-hidden="true"><span class="octicon octicon-link"></span></a>Historique du site depuis 1970</h2>`

How to solve this issue ?

**Comment by it-is-wednesday** [comment]
Seems like [this PR](https://github.com/toshimaru/jekyll-toc/pull/79) broke it. I'm new to this project and don't really know ruby, so I'd just advise to specify version 0.10.0 in your Gemfile

**Comment by jfiger** [comment]
Yes. Thank you. I don't understand this PR because the generated code was already HTML5 compliant.
