### ISSUE TITLE
How to enable by default for all pages

### ISSUE THREAD

**Issue by axilleas** [toshimaru/jekyll-toc#116]
Hi! Thanks for the plugin! How is it possible to enable this by default for all pages? Here's a PR where I'm trying to enable this for some pages https://github.com/home-assistant/home-assistant.io/pull/13572/files.

In short:

1. I'm using `{% toc %}` since this is applied in an aside.
1. The pages I'm trying to enable this are [defined as collections ](https://github.com/home-assistant/home-assistant.io/blob/1309644f4b590fe85b21e9a48946317ef1e67980/_config.yml#L66-L68).
1. `toc: true` is defined in the [`_config.yaml` defaults ](https://github.com/home-assistant/home-assistant.io/blob/1309644f4b590fe85b21e9a48946317ef1e67980/_config.yml#L114-L126).

Still, the ToC doesn't appear. If I set it explicitly in a page's frontmatter, it works, but I want to avoid that though since there are 1000+ pages this should be applied to.

Any help would be appreciated, thanks!

**Comment by Potherca** [comment]
I'm just a casual user, but I had the same sort of issue. Setting `toc` in the defaults with an empty `path` and the collection as `type` worked for me:

```yml
defaults:
  -
    scope:
      path: ""
      type: "integrations"
    values:
      toc: true
```

If this doesn't help, it might be worth setting up a separate repo with a minimal use-case, to make sure it isn't something outside this plugin that is messing with things.

Looking at the code you linked to, you seem to be missing the required `path` for the `type: posts` entry.

> While type is optional, you must specify a value for path when creating a scope/values pair.

<sup>source: https://jekyllrb.com/docs/configuration/front-matter-defaults/<sup>

Not sure if that is mesing anything up but it might be worth fixing.

**Comment by axilleas** [comment]
@Potherca this worked! Thanks a lot for this :heart:

**Comment by frenck** [comment]
Hey @Potherca :)

Thanks for helping out 😉

**Comment by toshimaru** [comment]
I've added **Enable TOC by default** section to README. 👍  

https://github.com/toshimaru/jekyll-toc#enable-toc-by-default
