### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by XhmikosR** [toshimaru/jekyll-toc#25]
Hey, there.

So, in Bootstrap v4-dev we switched to your plugin.

I notice that the generated HTML is invalid.

See for example https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/about/brand.md

The HTML we get is the following, which is invalid:

```html
            <ul class="section-nav">
<ul>
<li class="toc-entry toc-h2"><a href="#contents">Contents</a></li>
<li class="toc-entry toc-h2"><a href="#mark-and-logo">Mark and logo</a></li>
</ul>
<li class="toc-entry toc-h1"><a href="#bootstrap">Bootstrap</a></li>
<li class="toc-entry toc-h1"><a href="#bootstrap-1">Bootstrap</a>
<ul>
<li class="toc-entry toc-h2"><a href="#download-mark">Download mark</a></li>
<li class="toc-entry toc-h2"><a href="#name">Name</a>
<ul>
<li class="toc-entry toc-h3"><a href="#bootstrap-2">Bootstrap</a></li>
<li class="toc-entry toc-h3"><a href="#bootstrap-3">BootStrap</a></li>
<li class="toc-entry toc-h3"><a href="#twitter-bootstrap">Twitter Bootstrap</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#colors">Colors</a></li>
</ul>
</li>
</ul>
```

/CC @mdo @johann-S

**Comment by mdo** [comment]
This isn't the plugin's fault, it's mine. Fixed this in https://github.com/twbs/bootstrap/commit/0d14fe9e881e4fadf9e57ab979ace39f3c36b3b5.

**Comment by XhmikosR** [comment]
Cool, thanks!

**Comment by XhmikosR** [comment]
There are many more we need to fix that only the official validator will warn ;)

**Comment by toshimaru** [comment]
thanks for reporting!

if any other issue or concern, please let me know!

**Comment by XhmikosR** [comment]
@toshimaru: now that I looked into this closer, I do believe we could benefit from an ignore function.

Our docs use `.bd-example` for the examples; we basically don't want those in the TOC and this results to invalid HTML because the header hierarchy is pretty random. For example, we have an `h3` before the `div.bd-example`, and into that `div` we have `h6`; then jekyll-toc nests that into another `ul` which results in invalid HTML.

**Comment by XhmikosR** [comment]
@toshimaru: I still think it's wrong HTML on your plugin's side. You seem to be adding a new `ul` inside a `ul` in these lines: https://github.com/toshimaru/jekyll-toc/blob/master/lib/table_of_contents/parser.rb#L95-L101

**Comment by toshimaru** [comment]
@XhmikosR Thanks for sending PR! Could you give me an example to reproduce this issue?

> https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/about/brand.md

This link you gave still generates invalid HTML?

**Comment by XhmikosR** [comment]
@toshimaru: check out the repo, and do `bundle i && bundle exec jekyll build`.

Without #32: https://gist.github.com/XhmikosR/9e417efb51b3b7b86c8502c8bb36b7a0
with #32: https://gist.github.com/XhmikosR/1980d50634271f3dccad173306c5b3ef

**Comment by XhmikosR** [comment]
The `error: Element "ul" not allowed as child of element "ul" in this context. (Suppressing further errors from this subtree.)` errors are gone now.

**Comment by XhmikosR** [comment]
The other errors we mostly ignore them, see https://github.com/twbs/bootstrap/pull/24149

**Comment by toshimaru** [comment]
I tried it, but I didn't get any error.

```console
➜  bootstrap git:(v4-dev) bundle exec jekyll build
Configuration file: /Users/toshimaru/src/github.com/twbs/bootstrap/_config.yml
            Source: .
       Destination: ./_gh_pages
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 7.887 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Something I missed? @XhmikosR

**Comment by XhmikosR** [comment]
The errors aren't build errors. Try validating the result HTML with the
official validator.

On Sep 30, 2017 18:41, "Toshimaru" <notifications@github.com> wrote:

I tried it, but I didn't get any error.

➜  bootstrap git:(v4-dev) bundle exec jekyll buildConfiguration file:
/Users/toshimaru/src/github.com/twbs/bootstrap/_config.yml
Source: .       Destination: ./_gh_pages Incremental build: disabled.
Enable with --incremental      Generating...                    done
in 7.887 seconds. Auto-regeneration: disabled. Use --watch to enable.

Something I missed? @XhmikosR <https://github.com/xhmikosr>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/toshimaru/jekyll-toc/issues/25#issuecomment-333316657>,
or mute the thread

**Comment by toshimaru** [comment]
@XhmikosR Hi, I've given it a try in #33. Can you test my branch in you local environment?

**Comment by XhmikosR** [comment]
@toshimaru: confirmed, it fixes the errors. I'm gonna close my PR.

Thanks!

**Comment by toshimaru** [comment]
Hi, @XhmikosR I've just release [v0.4.0.rc](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.4.0.rc). Can you try it out and please let me know if any issues.

**Comment by XhmikosR** [comment]
@toshimaru: thanks! I tested this in our `html-linting` branch and I still get one error there:

```
C:\Users\xmr\Desktop\bootstrap>npm run docs-lint

> bootstrap@4.0.0-beta docs-lint C:\Users\xmr\Desktop\bootstrap
> node build/htmllint.js

"file:/C:/Users/xmr/Desktop/bootstrap/_gh_pages/docs/4.0/components/alerts/index.html":587.1-587.4: error: Element "ul" not allowed as child of element "ul" in this context. (Suppressing further errors from this subtree.)
```

**Comment by XhmikosR** [comment]
This is the related HTML:

```html
            <ul class="section-nav">
<li class="toc-entry toc-h2"><a href="#examples">Examples</a>
<ul>
<ul>  <!--ERROR-->
<li class="toc-entry toc-h4"><a href="#conveying-meaning-to-assistive-technologies">Conveying meaning to assistive technologies</a></li>
</ul>
<li class="toc-entry toc-h3"><a href="#link-color">Link color</a></li>
<li class="toc-entry toc-h3"><a href="#additional-content">Additional content</a>
<ul>
<li class="toc-entry toc-h4"><a href="#well-done">Well done!</a></li>
</ul>
</li>
<li class="toc-entry toc-h3"><a href="#dismissing">Dismissing</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#javascript-behavior">JavaScript behavior</a>
<ul>
<li class="toc-entry toc-h3"><a href="#triggers">Triggers</a></li>
<li class="toc-entry toc-h3"><a href="#methods">Methods</a></li>
<li class="toc-entry toc-h3"><a href="#events">Events</a></li>
</ul>
</li>
</ul>
```

**Comment by XhmikosR** [comment]
If I change the `Examples` header to `h2` then there is no error. I still believe this is an issue and should be handled because you can't expect people to use a specific header :)

**Comment by toshimaru** [comment]
hmm, I'm gonna give it another try.

**Comment by toshimaru** [comment]
Hello, @XhmikosR , I've just released [v0.4.0.rc2](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.4.0.rc2)! Could you try again?

**Comment by XhmikosR** [comment]
@toshimaru: seems to work fine now, thanks!

**Comment by toshimaru** [comment]
:+1: 

thanks for your contribution!!

**Comment by toshimaru** [comment]
just let you know, this change is officially releases as [v0.4.0](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.4.0)
