### ISSUE TITLE
Not Working on Jekyll 4.5.1

### ISSUE THREAD

**Issue by vahid-dan** [toshimaru/jekyll-toc#27]
Hi;

I have a website with Jekyll 4.5.1 and it seems this plugin is not working on that, not in pages, nor in layouts.

Thanks,
Vahid

**Comment by toshimaru** [comment]
Probably you mean Jekyll 3.5.1?

https://rubygems.org/gems/jekyll/versions

I tries it out on [my blog repo](https://github.com/toshimaru/blog.toshimaru.net/) and it does work.

```
$ bundle list | grep jekyll
  * jekyll (3.5.1)
  * jekyll-coffeescript (1.0.2)
  * jekyll-compose (0.4.1 005b2af)
  * jekyll-feed (0.9.2)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (1.5.0)
  * jekyll-sitemap (1.1.1)
  * jekyll-tagging (1.1.0)
  * jekyll-tagging-related_posts (1.0.0)
  * jekyll-toc (0.3.0)
  * jekyll-watch (1.5.0)

$ bundle exec jekyll build
Configuration file: /Users/toshimaru/github.com/toshimaru/blog.toshimaru.net/_config.yml
            Source: /Users/toshimaru/github.com/toshimaru/blog.toshimaru.net
       Destination: /Users/toshimaru/github.com/toshimaru/blog.toshimaru.net/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 9.343 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

If you have any further information, please feel free to re-open issue with reproduce steps.

**Comment by vahid-dan** [comment]
Hi @toshimaru and thanks a lot for your reply.

I tested it again and I found out it is working when I explicitly add `toc: true` to the front matter of a page. But I thought when I add it to the front matter of a layout, all the pages with that layout would get it. But it is not working that way. Did I have a wrong expectation? Is there any way to do that?

Thanks,
Vahid

**Comment by vahid-dan** [comment]
@toshimaru,

Nevermind! I just made it work for my whole layout by adding `toc: true` to the default settings of the layout in `_config.yml`.

Thanks a lot for your great plugin and support. :-)

Cheers,
Vahid
