### ISSUE TITLE
how to limit the depth of the TOC?

### ISSUE THREAD

**Issue by tahaykACF** [toshimaru/jekyll-toc#31]
is it possible to limit the depth of the TOC ? l

**Comment by XhmikosR** [comment]
Yeah, this is a must addition; there should be an option for `min` and `max`.

**Comment by tahaykACF** [comment]
the workaround for now is to use the css:

```css
.toc-entry.toc-h1,
.toc-entry.toc-h2
{}
.toc-entry.toc-h3,
.toc-entry.toc-h4,
.toc-entry.toc-h5,
.toc-entry.toc-h6
{
  display: none;
}
```

**Comment by XhmikosR** [comment]
Proper configuration support would be welcome and would make things way
more flexible.

On Oct 1, 2017 11:52, "tahaykACF" <notifications@github.com> wrote:

Closed #31 <https://github.com/toshimaru/jekyll-toc/issues/31>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/toshimaru/jekyll-toc/issues/31#event-1273006945>, or mute
the thread

**Comment by toshimaru** [comment]
@tahaykACF @XhmikosR  Thank you guys for the feedback!

Which feature do you want, global depth configuration or per-post depth configuraton? Or both of this?

For now, I'd say using CSS `display: none;` is enough.

**Comment by XhmikosR** [comment]
@toshimaru: Personally I believe it should be a global option as a first step because usually most people follow some kind of order. In our case in Bootstrap, it would be enough to specify a specific selector for example.

**Comment by toshimaru** [comment]
Thanks, I'm gonna re-consider this feature and reopen the issue.

**Comment by XhmikosR** [comment]
@toshimaru: any news about this? In our case it results in broken links.

See for example: https://validator.w3.org/checklink?uri=https%3A%2F%2Fgetbootstrap.com%2Fdocs%2F4.0%2Fcomponents%2Fscrollspy%2F&hide_type=all&depth=&check=Check

While it might not be visible to end users, not sure how search bots interpreter this...

So passing a specific or specific selectors should fix such issues.

**Comment by toshimaru** [comment]
@XhmikosR I confirmed the error. I'm gonna add this feature!

```
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://getbootstrap.com/docs/4.0/components/scrollspy/#item-4 (line 617)
https://getbootstrap.com/docs/4.0/components/scrollspy/#item-2-1 (line 615)
https://getbootstrap.com/docs/4.0/components/scrollspy/#item-2-2 (line 600)
```

**Comment by XhmikosR** [comment]
@toshimaru: ideally, the best would be if one could specify headers to ignore, like `.bd-example h4` etc.

Should I make a new issue?

**Comment by toshimaru** [comment]
Yes, please create new one. :)

**Comment by toshimaru** [comment]
@XhmikosR @tahaykACF  I just relaseed [v0.5.0.rc](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.5.0.rc), which allows you to configure min heading level and max level.

`_config.yml`:

```yml
toc:
  min_level: 1
  max_level: 5
```

**Comment by XhmikosR** [comment]
Seems to works fine, thanks!

Now if we could exclude specific headers, this would be the perfect jekyll TOC plugin :)

**Comment by toshimaru** [comment]
[v0.5.0](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.5.0) has been released. Thanks guys 😼
