### ISSUE TITLE
Allow specifying headers to ignore

### ISSUE THREAD

**Issue by XhmikosR** [toshimaru/jekyll-toc#37]
In our use case we never want the following to be included in the TOC:

```html
<h2>foo</h2>

<h3>bar</h3>

<div class="bd-example">
  <p>text</p>
  <h4>header</h4> <!-- we need to ignore this -->
</div>

<h3>bar</h3>
```

**Comment by toshimaru** [comment]
@XhmikosR I'm sorry to have kept you waiting, in [v0.7.0](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.7.0), `no_toc` option has been released❗️Please give a try 😸

**Comment by chalin** [comment]
\o/

**Comment by XhmikosR** [comment]
Thanks, I'll try it tomorrow or so, and let you know!
