### ISSUE TITLE
Does not work with GitHub Pages

### ISSUE THREAD

**Issue by davidculley** [toshimaru/jekyll-toc#49]
When I develop locally with `bundle exec jekyll serve`, everything works like it should. When I push my changes to GitHub, however, there's no TOC in my posts.

**Comment by toshimaru** [comment]
https://github.com/toshimaru/jekyll-toc/issues/29#issuecomment-327203625

**Comment by davidculley** [comment]
Oops, didn't see there already was an issue. Thank you for the quick response!
