### ISSUE TITLE
`ignore_within` doesn't seem to work

### ISSUE THREAD

**Issue by XhmikosR** [toshimaru/jekyll-toc#60]
Hi.

So I tried the new version with our Bootstrap docs with version 0.7.1 and it doesn't seem to work...

```yml
toc:
  ignore_within:    ".bd-example"
  min_level:        2
  max_level:        4
```

```html
<div class="bd-example">
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
  <hr>
  <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
</div>
</div>
```

I also tried `bd-example` which doesn't seem to work either. I'm still getting `Well done!` in ToC.

PR: https://github.com/twbs/bootstrap/pull/27417
Live preview: https://deploy-preview-27417--twbs-bootstrap4.netlify.com/docs/4.1/components/alerts/

**Comment by XhmikosR** [comment]
Oops, it seems `ignore_within` isn't released yet :)

**Comment by XhmikosR** [comment]
Closing, since it actually seems to work fine :)

I'm gonna wait for the stable release to update.

**Comment by toshimaru** [comment]
Hi, @XhmikosR, I've just released [v0.8.0.rc1](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.8.0.rc1).

If you wanna try `no_toc_section` feature, please try the version and give me feedback.

**Usage**: just add `no_toc_section` class to `<div>` you want to ignore(no need to modify `_config.yml`).

**Comment by XhmikosR** [comment]
We currently don't have any such case @toshimaru :)

But I quickly tested and it seems to work fine.

**Comment by XhmikosR** [comment]
@toshimaru: this seems to be broken in 0.8.0 for the Netlify's previews, which is using Ruby 2.3.6, but works locally for me with Ruby 2.4.2.

If you check https://deploy-preview-27417--twbs-bootstrap4.netlify.com/docs/4.1/components/alerts/ you will see it includes `Well done!` in ToC.

Maybe it's something on Netlify only but I thought I'd report it.

**Comment by XhmikosR** [comment]
OK apparently you changed this.

**Comment by XhmikosR** [comment]
Unfortunately we need more than one class in Bootstrap. Not a big deal since I actually found a way to work around this, but if there's no (huge) performance hit, this would be very handy. :)

**Comment by toshimaru** [comment]
Okay, could you create a issue about multiple no_toc_section?
