### ISSUE TITLE
Allow adding customizing `ul` class/ID

### ISSUE THREAD

**Issue by XhmikosR** [toshimaru/jekyll-toc#67]
It seems currently there's no way to change the `ul.section-nav`. Adding an ID/class would make this a lot more flexible.

**Comment by toshimaru** [comment]
Related? 

> Allow specifying custom class names #15

**Comment by XhmikosR** [comment]
If you plan on allowing to pass an ID then it's the same :)

**Comment by N7K4** [comment]
You can check my [PR 94](https://github.com/toshimaru/jekyll-toc/pull/94). I have add the ul class and also a jump back to the top link
