### ISSUE TITLE
Option for an ordered list

### ISSUE THREAD

**Issue by jp26jp** [toshimaru/jekyll-toc#71]
Please add this option. Love the plugin!

**Comment by toshimaru** [comment]
I've just release [v0.15.0.rc](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.15.0.rc) which supports ordered list.

If you have any issue, please let me know.

(cc/ @zsyed91 )

**Comment by toshimaru** [comment]
jekyll-toc [v0.15.0](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.15.0) has been releases ❗
