### ISSUE TITLE
`inject-anchors` injects invalid HTML

### ISSUE THREAD

**Issue by derpmarine168** [toshimaru/jekyll-toc#73]
imject-anchors is injectiong invalid html with duplicate IDs.
the code `heading one` generates 
```html
<h1 id="header-one">↩
<a id="header-one" class="anchor" href="#header-one" aria-hidden="true"><span class="octicon octicon-link"></span></a>Header one</h1>↩
```
and that is invalid HTML as it contains duplicate IDs. This is poor practice and may cause errors in some browsers.

**Comment by toshimaru** [comment]
@derpmarine168 , Thank you for reporting issue. It was resolved by #79. Please use v0.11.0.
