### ISSUE TITLE
New {% toc %} tag only available in posts and collections

### ISSUE THREAD

**Issue by traductik** [toshimaru/jekyll-toc#85]
Hello,
The new tag scheme disturbs the layout of my site since I have TOC  content in asides for contents other that posts and collections in my sites. Could you please advise me some workaround for this? Apart from this, thanks for jekyll-toc, Toshimaru, this  is a very handy addition!
Frédéric Salard-Deschandol, from Nice, France

**Comment by traductik** [comment]
By the way, I have found a workaround: gather the pages I wanted to "TOCify" in some collections. And it worked! Thanks again...

**Comment by toshimaru** [comment]
@traductik  Thanks for the information!!! 

Does anyone have the same issue ❓ 
（If many, I'm considering removing deprecation message）

**Comment by zoltan-baba** [comment]
When you only have a default.html containing the layout for the articles (articles are defined as a collection but there is no articles.html), the {% toc %} tag simply doesn't work. Please keep toc_only available - that still does the job.

**Comment by sustained** [comment]
Seems like a strange limitation, I want to put the TOC in an aside, way away from the content. But it just doesn't work because the codebase isn't using collections. And I'm not going to change it all just so we can use TOC, so personally I'll have to find another library.
